DATABASE = 'sqlite:///example.db'
#LOGFILE = '/var/log/poobrains.log'
DEBUG = True
#PROPAGATE_EXCEPTIONS = True
MAY_INSTALL = True
SECRET_KEY = 'Fnord'
THEME = 'default'
PAGINATION_COUNT = 2
TOKEN_VALIDITY=60
CA_KEY = '/var/www/poobrains/ssl/websrv.key'
CA_CERT = '/var/www/poobrains/ssl/webca.crt'
