DATABASE = 'sqlite:///example.db'
#LOGFILE = '/var/log/poobrains.log'
DEBUG = True
#PROPAGATE_EXCEPTIONS = True
MAY_INSTALL = True
SECRET_KEY = 'Fnord'
THEME = 'default'
PAGINATION_COUNT = 2
TOKEN_VALIDITY=60
CA_KEY = 'ssl/webca.key'
CA_CERT = 'ssl/webca.crt'
