DATABASE = 'sqlite:///poobrains.db' # database url, containing password, if any. at least sqlite and postres should be supported
LOGFILE = False # examples: 'poobrains.log', '/var/log/poobrains.log'
THEME = 'default'
PAGINATION_COUNT = 10
TOKEN_VALIDITY = 600
MAX_TOKENS = 5 # maximum number of allowed clientcert tokens for a single user
CERT_LIFETIME = 60 * 60 * 24 * 7 # TODO: Shouldn't this be user-selectable at time of certificate provisioning?
GPG_HOME = None # str, path
GPG_SIGNKEY = None # str, a gpg key fingerprint
GPG_PASSPHRASE = None # str, gpg key passphrase for signing
SMTP_HOST = None # str, ip address or dns name
SMTP_PORT = None # int
SMTP_ACCOUNT = None # str
SMTP_PASSWORD = None # str
